language: scala
scala:
   - 2.11.7
jdk:
  - oraclejdk8
  
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
  - "$HOME/downloads"

notifications:
  email:
    recipients:
      - connekt-dev@flipkart.com
      - kinshuk.bairagi@flipkart.com
env:
  global:
    - CI_HOME=`pwd`

branches:
  only:
    - master

before_install:
  - csq=`mktemp -d -t csq.XXX`
  - git clone --depth=10 --branch=hbase1.2 https://github.com/kingster/chronosq chronosq
  - pushd chronosq > /dev/null
  - mvn install -DskipTests=true -B -V
  - popd > /dev/null
  - git clone --depth=10 --branch=master https://github.com/relayrides/pushy pushy
  - pushd pushy > /dev/null
  - mvn install -DskipTests=true -B -V
  - popd > /dev/null
  - git clone https://gist.github.com/f33ad41bac5e4550a3b2dbccf4a4a77b.git ckt-concord
  - pushd ckt-concord > /dev/null
  - sbt publishM2
  - popd > /dev/null

script:
  - sbt ++$TRAVIS_SCALA_VERSION assembly


